const lifeEmotionsData = [
  {
    "Stage": "Birth",
    "Emotion1": "Innocence",
    "Emotion2": "Curiosity",
    "Emotion3": "Joy",
    "Emotion4": "Wonder",
    "Percentage1": 25,
    "Percentage2": 20,
    "Percentage3": 30,
    "Percentage4": 25,
  },
  {
    "Stage": "School",
    "Emotion1": "Learning",
    "Emotion2": "Friendship",
    "Emotion3": "Excitement",
    "Emotion4": "Challenges",
    "Percentage1": 20,
    "Percentage2": 25,
    "Percentage3": 15,
    "Percentage4": 40,
  },
  {
    "Stage": "College",
    "Emotion1": "Exploration",
    "Emotion2": "Growth",
    "Emotion3": "Independence",
    "Emotion4": "Friendships",
    "Percentage1": 25,
    "Percentage2": 20,
    "Percentage3": 30,
    "Percentage4": 25,
  },
  {
    "Stage": "Job",
    "Emotion1": "Achievement",
    "Emotion2": "Professional Fulfillment",
    "Emotion3": "Learning",
    "Emotion4": "Challenge",
    "Percentage1": 30,
    "Percentage2": 25,
    "Percentage3": 15,
    "Percentage4": 30,
  },
  {
    "Stage": "Marriage",
    "Emotion1": "Love",
    "Emotion2": "Commitment",
    "Emotion3": "Partnership",
    "Emotion4": "Growth",
    "Percentage1": 25,
    "Percentage2": 30,
    "Percentage3": 20,
    "Percentage4": 25,
  },
  {
    "Stage": "Kids",
    "Emotion1": "Parenthood",
    "Emotion2": "Joy",
    "Emotion3": "Responsibility",
    "Emotion4": "Connection",
    "Percentage1": 30,
    "Percentage2": 25,
    "Percentage3": 20,
    "Percentage4": 25,
  },
  {
    "Stage": "Old Age",
    "Emotion1": "Reflection",
    "Emotion2": "Fulfillment",
    "Emotion3": "Legacy",
    "Emotion4": "Contentment",
    "Percentage1": 20,
    "Percentage2": 25,
    "Percentage3": 30,
    "Percentage4": 25,
  },
];

export default lifeEmotionsData;
